### PR TITLE
Merge upstream changes

### LINKED ISSUE #5: Merge conflicts with spec master
There are a few merge conflicts between this repo and the spec master branch:
```
CONFLICT (content): Merge conflict in document/core/syntax/instructions.rst
[...]
CONFLICT (content): Merge conflict in document/core/appendix/index-instructions.rst
```
This prevents the [testsuite mirror](https://github.com/WebAssembly/testsuite)'s update script from updating the sign-extension-ops tests.

### PR DESCRIPTION
**Pull request by sbc100**
Fixes #5

### CODE REVIEW

**Comment by sbc100** [comment]
Since there were conflict I'd like to test the result of the merge.  What tests should I run in order to do that?

**Review by rossberg — APPROVED** [review]
Oops, missed this one.

Rubber-stamped, or is there anything specific you'd want me to watch out for?

**Comment by binji** [comment]
Let's merge this as-is, I'll do a quick directory diff against the spec to see if it all looks reasonable.

**Comment by binji** [comment]
Here's the diff: https://gist.github.com/binji/ab7c460da186d8c69e4d10b52c513527

**Comment by rossberg** [comment]
Thanks, that is super useful. Why not add a section to the proposal howto that explains how to generate these. :)

From a quick glance, it looks like the alignment of the instruction table is off, which will probably make Sphinx spit warnings.

**Comment by sbc100** [comment]
You mean how to generate the diff?  Isn't that just `git diff upstream/master..origin/master`?   Where upstream is the main spec repo?

**Comment by binji** [comment]
Yep, that looks like the same thing. Forgot you could do that, and did it the old-fashioned way with `diff -r <upstream dir> <proposal dir>`. But this is better :)

**Comment by binji** [comment]
Oops, accidentally merged without PR. PTAL: https://github.com/WebAssembly/proposals/commit/fcacca3768c1736cc935e8f5d05ca8efc6e02666

**Comment by rossberg** [comment]
Thanks!

**Pull request merged**
